services:

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge