"""Created Job Postning and Applicant Table

Revision ID: 90cf7ea696db
Revises: 79a0cf031035
Create Date: 2025-08-21 06:08:23.221824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90cf7ea696db'
down_revision: Union[str, Sequence[str], None] = '79a0cf031035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('recruiter_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=False),
    sa.Column('skills_required', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('job_type', sa.Enum('full-time', 'part-time', 'internship', 'contract', name='job_type_enum'), nullable=False),
    sa.Column('salary_range', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'draft', name='job_status_enum'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['recruiter_id'], ['recruiters.recruiter_id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('applications',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('applicant_id', sa.UUID(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('applied', 'under review', 'shortlisted', 'rejected', 'hired', name='application_status_enum'), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['applicants.applicant_id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.job_id'], ),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('application_id')
    )
    op.add_column('applicants', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('applicants', 'experience',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('applicants', 'education',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(None, 'companies', ['company_id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'companies', type_='unique')
    op.alter_column('applicants', 'education',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('applicants', 'experience',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('applicants', 'skills')
    op.drop_table('applications')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
