name: FastAPI Unit Tests
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: 
  

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses:  actions/setup-python@v5
        with: 
          python-version-file: ".python-version"

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.15"
      
      - name: Verify Installs
        run: |
          python --version
          uv --version
      
      - name: Install Dependencies
        run: |
          uv sync --locked --dev

      - name: Run Tests with Coverage
        run: |
          uv run pytest -q --cov
      
